import ctypes

hand_modbus_register = {
    'HAND_ID':                  {'addr': 1000, 'unit': ctypes.c_byte, 'length': 1},
    'REDU_RATIO':               {'addr': 1002, 'unit': ctypes.c_byte, 'length': 1},
    'CLEAR_ERROR':              {'addr': 1004, 'unit': ctypes.c_byte, 'length': 1},
    'SAVE':                     {'addr': 1005, 'unit': ctypes.c_byte, 'length': 1},
    'RESET_PARA':               {'addr': 1006, 'unit': ctypes.c_byte, 'length': 1},
    'GESTURE_NO_SET':           {'addr': 1008, 'unit': ctypes.c_byte, 'length': 1},
    'GESTURE_FORCE_CLB':        {'addr': 1009, 'unit': ctypes.c_byte, 'length': 1},
    'CURRENT_LIMIT':            {'addr': 1020, 'unit': ctypes.c_short,'length': 6},
    'DEFAULT_SPEED_SET':        {'addr': 1032, 'unit': ctypes.c_short,'length': 6},
    'DEFAULT_FORCE_SET':        {'addr': 1044, 'unit': ctypes.c_short,'length': 6},
    'USER_DEF_ANGLE':           {'addr': 1066, 'unit': ctypes.c_short,'length': (32, 6)},
    'CONTROL_MODE':             {'addr': 1470, 'unit': ctypes.c_short,'length': 1},
    'VOLTAGE':                  {'addr': 1472, 'unit': ctypes.c_short,'length': 1},
    'POS_SET':                  {'addr': 1474, 'unit': ctypes.c_short,'length': 6},
    'ANGLE_SET':                {'addr': 1486, 'unit': ctypes.c_short,'length': 6},
    'FORCE_SET':                {'addr': 1498, 'unit': ctypes.c_short,'length': 6},
    'SPEED_SET':                {'addr': 1522, 'unit': ctypes.c_short,'length': 6},
    'POS_ACT':                  {'addr': 1534, 'unit': ctypes.c_short,'length': 6},
    'ANGLE_ACT':                {'addr': 1546, 'unit': ctypes.c_short,'length': 6},
    'FORCE_ACT':                {'addr': 1582, 'unit': ctypes.c_short,'length': 6},
    'CURRENT':                  {'addr': 1594, 'unit': ctypes.c_short,'length': 6},
    'ERROR':                    {'addr': 1606, 'unit': ctypes.c_byte,'length': 6},
    'STATUS':                   {'addr': 1612, 'unit': ctypes.c_byte,'length': 6},
    'TEMP':                     {'addr': 1618, 'unit': ctypes.c_byte,'length': 6},
    'CMD_FINGER_MODE_B':        {'addr': 1625, 'unit': ctypes.c_byte,'length': 6},
    'ACTION_SEQ_CHECKDATA1':    {'addr': 2000, 'unit': ctypes.c_byte,'length': 1},
    'ACTION_SEQ_CHECKDATA2':    {'addr': 2001, 'unit': ctypes.c_byte,'length': 1},
    'ACTION_SEQ_STEPNUM':       {'addr': 2002, 'unit': ctypes.c_byte,'length': 1},
    'ACTION_SEQ_STEP_0':        {'addr': 2016, 'unit': ctypes.c_short,'length': 19},
    'ACTION_SEQ_STEP_1':        {'addr': 2054, 'unit': ctypes.c_short,'length': 19},
    'ACTION_SEQ_STEP_2':        {'addr': 2092, 'unit': ctypes.c_short,'length': 19},
    'ACTION_SEQ_STEP_3':        {'addr': 2130, 'unit': ctypes.c_short,'length': 19},
    'ACTION_SEQ_STEP_4':        {'addr': 2168, 'unit': ctypes.c_short,'length': 19},
    'ACTION_SEQ_STEP_5':        {'addr': 2206, 'unit': ctypes.c_short,'length': 19},
    'ACTION_SEQ_STEP_6':        {'addr': 2244, 'unit': ctypes.c_short,'length': 19},
    'ACTION_SEQ_STEP_7':        {'addr': 2282, 'unit': ctypes.c_short,'length': 19},
    'ACTION_SEQ_INDEX':         {'addr': 2320, 'unit': ctypes.c_byte,'length': 1},
    'SAVE_ACTION_SEQ':          {'addr': 2321, 'unit': ctypes.c_byte,'length': 1},
    'ACTION_SEQ_RUN':           {'addr': 2322, 'unit': ctypes.c_byte,'length': 1},
    'ACTION_ADJUST_FORCE_SET':  {'addr': 2324, 'unit': ctypes.c_byte,'length': 2},
}